apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
spec:
  instances: 3

  postgresql:
    parameters:
      max_connections: "400"
      wal_level: "logical"

  monitoring:
    enabled: true